### ISSUE TITLE
Training and Evaluation Code Availability

### ISSUE THREAD

**Issue by journey1234-liu** [RomStriker/Trexplorer#1]
Dear Author,
Thank you for your excellent work on centerline tracking! The training and evaluation code is currently unavailable now. I'd be very grateful if you can upload them.
Thank you.

**Comment by journey1234-liu** [comment]
Also, it would be better if the data preprocessing code can be released. Currently I am unaware of how to get the dataset folder ready.

**Comment by RomStriker** [comment]
Hi,

Thank you for your interest. I have updated the instructions for training and validation. I don't have a script ready for preprocessing the data, but I have described the required directory structure and I have shared example annotation files with description in [docs](https://github.com/RomStriker/Trexplorer/tree/abfb2296743d5c734476865aff732a7abed13936/docs). I might upload a preprocessing script later.

**Comment by journey1234-liu** [comment]
Thanks for your new updates!
